### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by almarklein** [imazen/freeimage#2]
Hi,

I read through http://sourceforge.net/p/freeimage/discussion/36111/thread/f2fae857/ and completely agree with you. What is the current status of this fork? E.g. it currently lags behind. And what about adding new features here? If you do that, you might reach a point where you cannot merge the "official" FI commits in.

**Comment by lilith** [comment]
We set up cross-platform CI for it and its dependencies (a rather difficult undertaking). We haven't changed any core code, really. 

That said, [FreeImage is in licensing limbo](http://sourceforge.net/p/freeimage/discussion/36111/thread/22c6c0bb/), and the maintainers aren't interested in collaboration. I've stopped investing in the project for now. If they fix the licensing and get rid of CVS that might change. 

I don't advocate use of the library as-is on untrusted image data; it is too easily exploited since the dependencies lag so far behind, and there is almost always an unfixed CVE.

**Comment by almarklein** [comment]
Are you aware of any alternatives? We rely on FreeImage in [imageio](https://github.com/imageio/imageio) a Python library for image reading/writing, and we would be happy to switch to something else if it'd be available (and compatible license-wise) ...

**Comment by lilith** [comment]
I've heard of https://github.com/OpenImageIO/oiio

My use case is less about diverse codec support and more about web image asset processing, so I haven't used it.
